name: Unity Package Semantic Versioning Auto Update

on: 
    push:
      branches:
        - 'upm'

jobs:
  update-version:
    name: 'Increment version number on upm'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Find Package Version
        uses: TB-Terence/upm-semver-update@upm
        with:
          package-json-path: './test/package.json'
          assembly-info-path: './test/Runtime/AssemblyInfo.cs'